notifications:
    email: false

language: generic
addons:
    apt:
        sources:
            - debian-sid
        packages:
            - shellcheck

script:
    - (
        for file in $(find script -type f -exec awk -f script/has-shebang.awk {} +);
        do
            ( set -x; shellcheck "${file}" );
        done
      )
