#!/usr/bin/env bash

set -e
set -u
set -o pipefail

download_raspbian_jessie_lite() {
    local destination_image_name="$1"

    [[ -f "$destination_image_name" ]] && return 0

    wget --no-clobber --quiet --show-progress \
        'https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2016-03-18/2016-03-18-raspbian-jessie-lite.zip'
    checksum=$(openssl dgst -SHA1 2016-03-18-raspbian-jessie-lite.zip | awk '{ print $2 }')
    if [[ $checksum != 'b78bb50bdac5ec8c108f34104f788e214ac23635' ]]
    then
        printf '%s\n' 'Bad checksum for download' >&2
        return 1
    fi

    unzip 2016-03-18-raspbian-jessie-lite.zip
    mv 2016-03-18-raspbian-jessie-lite.img "$destination_image_name"
}

execute_in_partition_context() {
    local image_name="$1"
    local partition_offset="$2"
    local partition_format="$3"
    shift 3
    local rootfs
    rootfs=$(basename "$(mktemp --dry-run)")

    mkdir -p "$rootfs"
    mount -v -o offset="$partition_offset" -t "$partition_format" "$image_name" "$rootfs"
    pushd "$rootfs"
        "$@"
    popd
    umount "$rootfs" && rmdir "$rootfs"
}

execute_in_container() {
    local preload="ld.so.preload"

    cp ./etc/$preload ../$preload
    truncate -s0 ./etc/$preload
    systemd-nspawn --directory "$(pwd)" "$@"
    mv ../$preload ./etc/$preload
}

update_linux() {
    local readonly hostname=${IMAGE_HOSTNAME:-raspberrypi}
    cp /usr/bin/qemu-arm-static ./usr/bin

    execute_in_container apt-get -y purge 'libraspberrypi-doc'
    execute_in_container apt-get -y clean
    execute_in_container apt-get -y autoremove

    cp -r "$dir"/files/* .

    printf '%s\n' "$hostname" > etc/hostname
    {
        printf '%s\n' "127.0.0.1 localhost"
        printf '%s\n' "127.0.1.1 $hostname"
    } > etc/hosts
}

update_bootp() {
    truncate -s0 config.txt
    {
        printf '%s\n' 'dtparam=i2c_arm=on'
        printf '%s\n' 'dtparam=spi=on'
        printf '%s\n' 'disable_camera_led=1'
        printf '%s\n' 'gpu_mem=128' 'start_x=1'
    } >> config.txt
}

build_custom_image() {
    local readonly dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    local readonly hostname=${IMAGE_HOSTNAME:-raspberrypi}

    download_raspbian_jessie_lite "raspbian-$hostname.img"
    linux_offset=$(fdisk -l "raspbian-$hostname.img" | awk -f "$dir"/fdisk-offsets.awk | awk '/Linux/ { print $2 }')
    bootp_offset=$(fdisk -l "raspbian-$hostname.img" | awk -f "$dir"/fdisk-offsets.awk | awk '/FAT32/ { print $2 }')
    execute_in_partition_context "raspbian-$hostname.img" "$linux_offset" 'ext4' update_linux
    execute_in_partition_context "raspbian-$hostname.img" "$bootp_offset" 'vfat' update_bootp
}

build_custom_image
